#! /bin/sh

#sxhkd &


#desktops=$(bspc query -M)

#echo "$desktops" | grep -q "[a-zA-Z]"
#if [ $? -eq 0 ]; then IsInitialRun=true; else IsInitialRun=false; fi

#i=1

#for monitor in $desktops; do
#  [ "$IsInitialRun" = true ] && \
#    bspc monitor "$monitor" -n $i -d $i/{00,01,10,11} || \
#    bspc monitor "$monitor" -d $i/{00,01,10,11}
#  let i++
#done
bspc monitor -d I II III IV V VI VII

bspc config border_width         0
bspc config window_gap          25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Xephyr state=tiled
